Vagrant.configure("2") do |config| 
  config.vm.box = "thtom/Fedora-35-Server-arm64-FR"
  config.vm.box_version = "1"
    
  # network
  config.vm.network "private_network", ip: "192.168.56.21"
  # config.vm.network "public_network"
    
  # synced folders
  #config.vm.synced_folder "../data", "/vagrant_data"
    
  # vm settings
  config.vm.provider "vmware_desktop" do |vmware|
    vmware.gui = true
    vmware.allowlist_verified = true
    # vmware.memory = "3096"
    # vmware.cpus = 2
  end
    
  # bash provision script
  config.vm.provision "shell", inline: <<-SHELL
    echo "exclude=kernel*" >> /etc/dnf/dnf.conf
    dnf update -y
    dnf install langpacks-en -y
    localectl set-locale LANG=en_US.UTF-8
    localectl set-keymap us
    dnf autoremove -y
    reboot now
  SHELL
end
