Vagrant.configure("2") do |config|
  # Webserver Apache2 Ubuntu 20.04 arm64
  config.vm.define "web01" do |web01|
    web01.vm.box = "bytesguy/ubuntu-server-20.04-arm64"
    web01.vm.network "private_network", ip: "192.168.40.11"
    web01.vm.provider "vmware_desktop" do |vmware|
      vmware.gui = true
      vmware.allowlist_verified = true
      vmware.memory = "1024"
      vmware.cpus = 2
    end
    web01.vm.provision "shell", inline: <<-SHELL
      apt update
      apt-mark hold linux-image-generic   linux-headers-generic
      apt install apache2 unzip -y
      apt autoremove -y
      cd /tmp/
      wget https://www.tooplate.com/zip-templates/2125_artxibition.zip
      unzip -o 2125_artxibition.zip
      cp -r 2125_artxibition/* /var/www/html/
    SHELL
  end

  # DB MariaDB Fedora 35 arm64
  config.vm.define "db01" do |db01|
    db01.vm.box = "jacobw/fedora35-arm64"
    db01.vm.network "private_network", ip: "192.168.40.12"
    db01.vm.synced_folder "../data", "/vagrant_data"
    db01.vm.provider "vmware_desktop" do |vmware|
      vmware.gui = true
      vmware.allowlist_verified = true
      vmware.memory = "1024"
      vmware.cpus = 2
    end
    db01.vm.provision "shell", inline: <<-SHELL
      echo "exclude=kernel*" >> /etc/dnf/dnf.conf
      dnf install mariadb-server -y
      dnf autoremove -y
      systemctl start mariadb
      systemctl enable mariadb
    SHELL
  end
end
