  Vagrant.configure("2") do |config| 
    config.vm.box = "jacobw/fedora35-arm64" 
    config.vm.network "private_network", ip: "192.168.56.12"
    config.vm.provider "vmware_desktop" do |vmware|
      vmware.gui = true
      vmware.allowlist_verified = true
    
    # bash provision script
    config.vm.provision "shell", inline: <<-SHELL
    echo "exclude=kernel*" >> /etc/dnf/dnf.conf
    dnf update -y
    dnf autoremove -y
    reboot now
    SHELL
    end
  end
